#include "CampaignCatalog.h"

#include <limits>

namespace Lostsense::Gameplay {
namespace {
const std::vector<CampaignQuestDefinition> kQuests{
    {80001U, CampaignAct::BellThatForgot, "The Returned",
     "Reach Bellgrave alive and meet Mara Venn.", 0U, 0U},
    {80002U, CampaignAct::BellThatForgot, "A Bell Without Sound",
     "Investigate the belfry and prove Bellgrave lost a shared event.", 0U, 0U},
    {80003U, CampaignAct::BellThatForgot, "Marks on the Ninth Cage",
     "Recover the expedition plate from Weeping Cut.", 20002U, 30003U},
    {80004U, CampaignAct::BellThatForgot, "Debt of the Foreman",
     "Find Ivo Salk and trace the Ninth Descent reroute.", 0U, 0U},
    {80005U, CampaignAct::BellThatForgot, "The Coinless Shaft",
     "Restore the cage brake, defeat the warden and descend.", 20003U, 0U},
    {80006U, CampaignAct::BellThatForgot, "Tongueless",
     "Defeat Odran and recover the first coherent senseprint.", 20003U, 30001U},
    {80010U, CampaignAct::RootsRememberBlood, "Black Sap",
     "Track the spreading memory sickness through Ravelwood.", 0U, 0U},
    {80011U, CampaignAct::RootsRememberBlood, "The Lives in Bark",
     "Extract senseprints without killing infected villagers.", 0U, 0U},
    {80012U, CampaignAct::RootsRememberBlood, "Fen Without Footsteps",
     "Reach Giltfen through the root tunnel that remembers a vanished road.", 0U,
     0U},
    {80013U, CampaignAct::RootsRememberBlood, "The Thorn Choir",
     "Discover the cult feeding memories into the forest.", 20005U, 0U},
    {80014U, CampaignAct::RootsRememberBlood, "Borrowed Mother",
     "Defeat Mother Veyr and resolve the abbey witness root.", 20005U, 30008U},
    {80020U, CampaignAct::CrownWithoutName, "A Capital That Denies Itself",
     "Enter Crownless Reach with Regent Solenne Mave.", 0U, 0U},
    {80021U, CampaignAct::CrownWithoutName, "The Missing Reign",
     "Recover royal ledgers whose rulers were erased.", 0U, 0U},
    {80022U, CampaignAct::CrownWithoutName, "Charter of Descent",
     "Expose the Gilded Charter's role in funding the Ninth Descent.", 0U, 0U},
    {80023U, CampaignAct::CrownWithoutName, "Empty Names",
     "Descend through the palace archive into contradictory royal histories.",
     20010U, 0U},
    {80024U, CampaignAct::CrownWithoutName, "The Regent-Engine",
     "Defeat Caldris and recover the unedited Ninth Descent contract.", 20010U,
     30017U},
    {80030U, CampaignAct::GoldRemembers, "Below the Charter Line",
     "Descend beyond legal mining depth.", 20019U, 0U},
    {80031U, CampaignAct::GoldRemembers, "Breath for the Dead",
     "Restart Deepworks ventilation without waking every archived miner.", 20019U,
     0U},
    {80032U, CampaignAct::GoldRemembers, "Royal Pressure",
     "Cross Pump Cathedral and stop the pressure collapse.", 20019U, 30024U},
    {80033U, CampaignAct::GoldRemembers, "The King's Bore",
     "Follow the Ninth Descent's real route through sealed royal excavation.",
     20022U, 0U},
    {80034U, CampaignAct::GoldRemembers, "A City in the Rock",
     "Defeat the Gilded Lung and breach an intact Namarith street.", 20022U,
     30026U},
    {80040U, CampaignAct::CityUnderSky, "Streets Before Kings",
     "Map the first Namarith district with Nera Quill.", 0U, 0U},
    {80041U, CampaignAct::CityUnderSky, "Consensus",
     "Operate civic anchors without accepting their memory edits.", 0U, 0U},
    {80042U, CampaignAct::CityUnderSky, "The Loom Annex",
     "Recover Namarith design records and the First Witness protocol.", 20026U,
     0U},
    {80043U, CampaignAct::CityUnderSky, "Seven Missing Years",
     "Locate a reconstruction chamber containing versions of the Returned.",
     20026U, 0U},
    {80044U, CampaignAct::CityUnderSky, "Keeper Ysil",
     "Defeat or release Ysil and access the Abyss breach.", 20026U, 30034U},
    {80050U, CampaignAct::HollowMeridian, "No Horizon",
     "Survive the first Abyss traversal using Quiet Assembly anchors.", 0U, 0U},
    {80051U, CampaignAct::HollowMeridian, "Serit No-Echo",
     "Negotiate entry into the Quiet House of Bearings.", 0U, 0U},
    {80052U, CampaignAct::HollowMeridian, "What the Loom Could Not Keep",
     "Recover proof that the Abyss is generated by rejected contradictions.",
     0U, 0U},
    {80053U, CampaignAct::HollowMeridian, "Blind Astrarium",
     "Reorient the observatory that maps absence instead of stars.", 20028U, 0U},
    {80054U, CampaignAct::HollowMeridian, "Cartographer of Nothing",
     "Defeat Kharos and reveal engineered entrances to the Red Archive.", 20028U,
     30041U},
    {80060U, CampaignAct::SecondSilence, "Bells at Noon",
     "Return to surface towns altered by synchronized Synod rituals.", 0U, 0U},
    {80061U, CampaignAct::SecondSilence, "The Mentor's Ledger",
     "Confront Oren Sile about the Ninth Descent.", 0U, 0U},
    {80062U, CampaignAct::SecondSilence, "A Mercy Measured in Names",
     "Choose which civilian archive to evacuate before the purge.", 0U, 0U},
    {80063U, CampaignAct::SecondSilence, "The Gallows Rewritten",
     "Assault the Synod surface relay network.", 20012U, 0U},
    {80064U, CampaignAct::SecondSilence, "Voice of Silence",
     "Defeat Sael Rhyne as the partial Second Silence begins.", 20012U, 30047U},
    {80070U, CampaignAct::RedArchive, "Into the Burn Layer",
     "Enter Hell through the Choirless breach.", 0U, 0U},
    {80071U, CampaignAct::RedArchive, "The Ember Compact",
     "Negotiate with Ossa Vark and the Ember Compact.", 0U, 0U},
    {80072U, CampaignAct::RedArchive, "Furnace Rights",
     "Disable quotas consuming newly erased surface senseprints.", 0U, 0U},
    {80073U, CampaignAct::RedArchive, "The Second Silence",
     "Chase Ilyr to the Foundry Cathedral.", 20034U, 0U},
    {80074U, CampaignAct::RedArchive, "Prelate in Ash",
     "Defeat Ilyr and uncover Aster's manipulation.", 20034U, 30055U},
    {80075U, CampaignAct::RedArchive, "The Door That Remembers You",
     "Open the Last Archive using the Returned's reconstruction record.", 0U,
     0U},
    {80080U, CampaignAct::FirstWitness, "Versions of Home",
     "Traverse curated reconstructions and identify their authored tells.",
     20036U, 0U},
    {80081U, CampaignAct::FirstWitness, "The Unresolved Key",
     "Free surviving Ninth Descent senseprints.", 20036U, 0U},
    {80082U, CampaignAct::FirstWitness, "Loom Below",
     "Shut down three consensus spines.", 20036U, 0U},
    {80083U, CampaignAct::FirstWitness, "First Witness",
     "Defeat Aster Null through the three evolving Sensewell phases.", 20036U,
     30060U},
    {80084U, CampaignAct::FirstWitness, "What Remains",
     "Choose Sever, Bind or Scatter after Aster's defeat.", 20036U, 0U},
};

const std::vector<CampaignRegionDefinition> kRegions{
    {1001U, "Bellgrave March", "Surface"},
    {1002U, "Ravelwood", "Surface / roots"},
    {1003U, "Giltfen", "Surface / wetland"},
    {1004U, "Crownless Reach", "Surface / urban ruin"},
    {1005U, "Saltglass Coast", "Surface / coast"},
    {1006U, "Stormspine Bastions", "Surface / highland"},
    {1007U, "Upper Vaur Goldworks", "Mine upper"},
    {1008U, "Royal Deepworks", "Mine deep"},
    {1009U, "Namarith Undercity", "Buried civilization"},
    {1010U, "Hollow Meridian", "Abyss"},
    {1011U, "Choirless Expanse", "Abyss"},
    {1012U, "Ashwake Wastes", "Red Archive"},
    {1013U, "Vask, City of Furnaces", "Red Archive city"},
    {1014U, "Bone-Tide Basilica", "Red Archive deep"},
    {1015U, "The Last Archive", "Final depths"},
};
} // namespace

const std::vector<CampaignQuestDefinition> &CampaignCatalog::Quests() {
  return kQuests;
}

const std::vector<CampaignRegionDefinition> &CampaignCatalog::Regions() {
  return kRegions;
}

std::optional<CampaignQuestDefinition>
CampaignCatalog::FindQuest(const std::uint32_t questId) {
  const auto index = QuestIndex(questId);
  if (index == std::numeric_limits<std::size_t>::max()) {
    return std::nullopt;
  }
  return kQuests[index];
}

std::optional<CampaignQuestDefinition>
CampaignCatalog::NextQuest(const std::uint32_t questId) {
  const auto index = QuestIndex(questId);
  if (index == std::numeric_limits<std::size_t>::max() ||
      index + 1U >= kQuests.size()) {
    return std::nullopt;
  }
  return kQuests[index + 1U];
}

std::size_t CampaignCatalog::QuestIndex(const std::uint32_t questId) noexcept {
  for (std::size_t index = 0; index < kQuests.size(); ++index) {
    if (kQuests[index].Id == questId) {
      return index;
    }
  }
  return std::numeric_limits<std::size_t>::max();
}

bool CampaignCatalog::IsCanonical() noexcept {
  if (kQuests.size() != 47U || kRegions.size() != 15U ||
      kQuests.front().Id != 80001U || kQuests.back().Id != 80084U) {
    return false;
  }
  std::uint8_t previousAct = 0U;
  std::uint32_t previousId = 0U;
  for (const auto &quest : kQuests) {
    const auto act = static_cast<std::uint8_t>(quest.Act);
    if (act < previousAct || quest.Id <= previousId || quest.Title.empty() ||
        quest.Objective.empty()) {
      return false;
    }
    previousAct = act;
    previousId = quest.Id;
  }
  return previousAct == static_cast<std::uint8_t>(CampaignAct::FirstWitness);
}

} // namespace Lostsense::Gameplay
